// ✓ tokens: ALL | layout: none | split: typed TS exports pointing to CSS vars

export const tokens = {
  colors: {
    heroBg: 'var(--color-hero-bg)',
    heroText: 'var(--color-hero-text)',
    heroSubtext: 'var(--color-hero-subtext)',
    highlightBar: 'var(--color-highlight-bar)',
    ctaPrimary: 'var(--color-cta-primary)',
    ctaPrimaryText: 'var(--color-cta-primary-text)',
    trustBarBg: 'var(--color-trust-bar-bg)',
    trustBarText: 'var(--color-trust-bar-text)',
    navLink: 'var(--color-nav-link)',
    navBtnBg: 'var(--color-nav-btn-bg)',
    navBtnText: 'var(--color-nav-btn-text)',
    logoRing: 'var(--color-logo-ring)',
    sectionBg: 'var(--color-section-bg)',
    sectionText: 'var(--color-section-text)',
    sectionSubtext: 'var(--color-section-subtext)',
    badgeBlue: 'var(--color-badge-blue)',
    badgeBlueText: 'var(--color-badge-blue-text)',
    badgePink: 'var(--color-badge-pink)',
    badgePinkText: 'var(--color-badge-pink-text)',
    cardBg: 'var(--color-card-bg)',
    cardBorderLeftBlue: 'var(--color-card-border-left-blue)',
    cardBorderLeftPink: 'var(--color-card-border-left-pink)',
    cardQuote: 'var(--color-card-quote)',
    starAccent: 'var(--color-star-accent)',
    black: 'var(--color-black)',
    white: 'var(--color-white)',
  },
  spacing: {
    s1: 'var(--space-1)',
    s2: 'var(--space-2)',
    s3: 'var(--space-3)',
    s4: 'var(--space-4)',
    s5: 'var(--space-5)',
    s6: 'var(--space-6)',
    s8: 'var(--space-8)',
    s10: 'var(--space-10)',
    s12: 'var(--space-12)',
    s16: 'var(--space-16)',
    s20: 'var(--space-20)',
    s24: 'var(--space-24)',
  },
  radius: {
    sm: 'var(--radius-sm)',
    md: 'var(--radius-md)',
    lg: 'var(--radius-lg)',
    pill: 'var(--radius-pill)',
  },
  shadows: {
    card: 'var(--shadow-card)',
    btn: 'var(--shadow-btn)',
  },
  font: {
    family: 'var(--font-family-primary)',
    light: 'var(--font-light)',
    regular: 'var(--font-regular)',
    medium: 'var(--font-medium)',
    semibold: 'var(--font-semibold)',
    bold: 'var(--font-bold)',
    extrabold: 'var(--font-extrabold)',
  },
} as const;

export type Tokens = typeof tokens;
